# Copyright (c) 2018 Serguei Kalentchouk. All rights reserved.
# Use of this source code is governed by an MIT license that can be found in the LICENSE file.
branches:
  only:
  - master

os: linux

language: cpp
compiler: gcc

install:
  - wget https://autodesk.box.com/shared/static/gloudjq6zljbg7br7o35vi82t158qcsd
  - tar -xvzf gloudjq6zljbg7br7o35vi82t158qcsd
  - mkdir maya2018
  - mv devkitBase/include maya2018/.
  - mv devkitBase/lib maya2018/.

script:
  - mkdir build
  - cd build
  - cmake ../. -G "CodeBlocks - Unix Makefiles" -DMAYA_LOCATION=$(pwd)/..
  - make
